In [184]:
import numpy as np
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers

In [185]:
import tensorflow as tf

In [186]:
import pandas as pd
wine = pd.read_csv('../Data/Wine.csv')

In [187]:
wine.shape

(178, 14)

In [188]:
wine.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

In [189]:
wine.Customer_Segment.value_counts()

2    71
1    59
3    48
Name: Customer_Segment, dtype: int64

In [190]:
wine.describe().transpose()

count        mean         std     min       25%  \
Alcohol               178.0   13.000618    0.811827   11.03   12.3625   
Malic_Acid            178.0    2.336348    1.117146    0.74    1.6025   
Ash                   178.0    2.366517    0.274344    1.36    2.2100   
Ash_Alcanity          178.0   19.494944    3.339564   10.60   17.2000   
Magnesium             178.0   99.741573   14.282484   70.00   88.0000   
Total_Phenols         178.0    2.295112    0.625851    0.98    1.7425   
Flavanoids            178.0    2.029270    0.998859    0.34    1.2050   
Nonflavanoid_Phenols  178.0    0.361854    0.124453    0.13    0.2700   
Proanthocyanins       178.0    1.590899    0.572359    0.41    1.2500   
Color_Intensity       178.0    5.058090    2.318286    1.28    3.2200   
Hue                   178.0    0.957449    0.228572    0.48    0.7825   
OD280                 178.0    2.611685    0.709990    1.27    1.9375   
Proline               178.0  746.893258  314.907474  278.00  500.5000   
Customer_Segment      178.0    1.938202    0.775035    1.00    1.0000   

                          50%       75%      max  
Alcohol                13.050   13.6775    14.83  
Malic_Acid              1.865    3.0825     5.80  
Ash                     2.360    2.5575     3.23  
Ash_Alcanity           19.500   21.5000    30.00  
Magnesium              98.000  107.0000   162.00  
Total_Phenols           2.355    2.8000     3.88  
Flavanoids              2.135    2.8750     5.08  
Nonflavanoid_Phenols    0.340    0.4375     0.66  
Proanthocyanins         1.555    1.9500     3.58  
Color_Intensity         4.690    6.2000    13.00  
Hue                     0.965    1.1200     1.71  
OD280                   2.780    3.1700     4.00  
Proline               673.500  985.0000  1680.00  
Customer_Segment        2.000    3.0000     3.00

In [191]:
for col in wine:
    print(col+": "+str(wine[col].nunique()))

Alcohol: 126
Malic_Acid: 133
Ash: 79
Ash_Alcanity: 63
Magnesium: 53
Total_Phenols: 97
Flavanoids: 132
Nonflavanoid_Phenols: 39
Proanthocyanins: 101
Color_Intensity: 132
Hue: 78
OD280: 122
Proline: 121
Customer_Segment: 3


In [192]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Alcohol               178 non-null    float64
 1   Malic_Acid            178 non-null    float64
 2   Ash                   178 non-null    float64
 3   Ash_Alcanity          178 non-null    float64
 4   Magnesium             178 non-null    int64  
 5   Total_Phenols         178 non-null    float64
 6   Flavanoids            178 non-null    float64
 7   Nonflavanoid_Phenols  178 non-null    float64
 8   Proanthocyanins       178 non-null    float64
 9   Color_Intensity       178 non-null    float64
 10  Hue                   178 non-null    float64
 11  OD280                 178 non-null    float64
 12  Proline               178 non-null    int64  
 13  Customer_Segment      178 non-null    int64  
dtypes: float64(11), int64(3)
memory usage: 19.6 KB


In [193]:
tf.test.gpu_device_name()

''

In [194]:
val_dataframe = wine.sample(frac=0.2, random_state=1337)

In [195]:
val_dataframe

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
44     13.05        1.77  2.10          17.0        107           3.00   
154    12.58        1.29  2.10          20.0        103           1.48   
133    12.70        3.55  2.36          21.5        106           1.70   
34     13.51        1.80  2.65          19.0        110           2.35   
21     12.93        3.80  2.65          18.6        102           2.41   
37     13.05        1.65  2.55          18.0         98           2.45   
70     12.29        1.61  2.21          20.4        103           1.10   
35     13.48        1.81  2.41          20.5        100           2.70   
25     13.05        2.05  3.22          25.0        124           2.63   
13     14.75        1.73  2.39          11.4         91           3.10   
32     13.68        1.83  2.36          17.2        104           2.42   
36     13.28        1.64  2.84          15.5        110           2.60   
96     11.81        2.12  2.74          21.5        134           1.60   
55     13.56        1.73  2.46          20.5        116           2.96   
107    12.72        1.75  2.28          22.5         84           1.38   
43     13.24        3.98  2.29          17.5        103           2.64   
39     14.22        3.99  2.51          13.2        128           3.00   
52     13.82        1.75  2.42          14.0        111           3.88   
106    12.25        1.73  2.12          19.0         80           1.65   
62     13.67        1.25  1.92          18.0         94           2.10   
24     13.50        1.81  2.61          20.0         96           2.53   
1      13.20        1.78  2.14          11.2        100           2.65   
54     13.74        1.67  2.25          16.4        118           2.60   
63     12.37        1.13  2.16          19.0         87           3.50   
19     13.64        3.10  2.56          15.2        116           2.70   
121    11.56        2.05  3.23          28.5        119           3.18   
135    12.60        2.46  2.20          18.5         94           1.62   
66     13.11        1.01  1.70          15.0         78           2.98   
128    12.37        1.63  2.30          24.5         88           2.22   
149    13.08        3.90  2.36          21.5        113           1.41   
120    11.45        2.40  2.42          20.0         96           2.90   
102    12.34        2.45  2.46          21.0         98           2.56   
124    11.87        4.31  2.39          21.0         82           2.86   
132    12.81        2.31  2.40          24.0         98           1.15   
118    12.77        3.43  1.98          16.0         80           1.63   
28     13.87        1.90  2.80          19.4        107           2.95   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity  \
44         3.00                  0.28             2.03             5.04   
154        0.58                  0.53             1.40             7.60   
133        1.20                  0.17             0.84             5.00   
34         2.53                  0.29             1.54             4.20   
21         2.41                  0.25             1.98             4.50   
37         2.43                  0.29             1.44             4.25   
70         1.02                  0.37             1.46             3.05   
35         2.98                  0.26             1.86             5.10   
25         2.68                  0.47             1.92             3.58   
13         3.69                  0.43             2.81             5.40   
32         2.69                  0.42             1.97             3.84   
36         2.68                  0.34             1.36             4.60   
96         0.99                  0.14             1.56             2.50   
55         2.78                  0.20             2.45             6.25   
107        1.76                  0.48             1.63             3.30   
43         2.63                  0.32             1.66            

In [196]:
val_dataframe.index

Int64Index([ 44, 154, 133,  34,  21,  37,  70,  35,  25,  13,  32,  36,  96,
             55, 107,  43,  39,  52, 106,  62,  24,   1,  54,  63,  19, 121,
            135,  66, 128, 149, 120, 102, 124, 132, 118,  28],
           dtype='int64')

In [197]:
train_dataframe = wine.drop(val_dataframe.index)

In [198]:
print(
    "Using %d samples for training and %d for validation"
    % (len(train_dataframe), len(val_dataframe)))

Using 142 samples for training and 36 for validation


In [199]:
# plot twist 1

# to-categorical is only applicable to tensorflow, same concept as one-hot encorder/ label encorder etc

from tensorflow.keras.utils import to_categorical   

In [200]:
def rep_x(x):
    if x == 1:
        return 0
    elif x == 2:
        return 1
    else:
        return 2

In [201]:
def dataframe_to_dataset(wine):
    wine = wine.copy()

    wine["Customer_Segment"]=wine["Customer_Segment"].apply(lambda x:rep_x(x))
    labels = to_categorical(wine.pop("Customer_Segment"))      # pop is remove and store
                            
    ds = tf.data.Dataset.from_tensor_slices((dict(wine), labels))
    ds = ds.shuffle(buffer_size=len(wine))
    return ds

In [202]:
train_ds = dataframe_to_dataset(train_dataframe)
val_ds = dataframe_to_dataset(val_dataframe)

In [203]:
for x, y in train_ds.take(1):
    print("Input:", x)
    print("Customer_Segment:", y)

Input: {'Alcohol': <tf.Tensor: shape=(), dtype=float64, numpy=13.05>, 'Malic_Acid': <tf.Tensor: shape=(), dtype=float64, numpy=5.8>, 'Ash': <tf.Tensor: shape=(), dtype=float64, numpy=2.13>, 'Ash_Alcanity': <tf.Tensor: shape=(), dtype=float64, numpy=21.5>, 'Magnesium': <tf.Tensor: shape=(), dtype=int64, numpy=86>, 'Total_Phenols': <tf.Tensor: shape=(), dtype=float64, numpy=2.62>, 'Flavanoids': <tf.Tensor: shape=(), dtype=float64, numpy=2.65>, 'Nonflavanoid_Phenols': <tf.Tensor: shape=(), dtype=float64, numpy=0.3>, 'Proanthocyanins': <tf.Tensor: shape=(), dtype=float64, numpy=2.01>, 'Color_Intensity': <tf.Tensor: shape=(), dtype=float64, numpy=2.6>, 'Hue': <tf.Tensor: shape=(), dtype=float64, numpy=0.73>, 'OD280': <tf.Tensor: shape=(), dtype=float64, numpy=3.1>, 'Proline': <tf.Tensor: shape=(), dtype=int64, numpy=380>}
Customer_Segment: tf.Tensor([0.000 1.000 0.000], shape=(3,), dtype=float32)


In [204]:
# popular batch number used is 32, 64, 128
train_ds = train_ds.batch(32)
val_ds = val_ds.batch(32)

In [205]:
# data pre-processing steps
from tensorflow.keras.layers import IntegerLookup    
from tensorflow.keras.layers import Normalization
from tensorflow.keras.layers import StringLookup

In [206]:
def encode_numerical_feature(feature, name, dataset):
    # Create a Normalization layer for our feature
    normalizer = Normalization()

    # Prepare a Dataset that only yields our feature (normalize the feature)
    feature_ds = dataset.map(lambda x, y: x[name])
    feature_ds = feature_ds.map(lambda x: tf.expand_dims(x, -1))

    # Learn the statistics of the data
    normalizer.adapt(feature_ds)

    # Normalize the input feature
    encoded_feature = normalizer(feature)
    return encoded_feature

****************************************************

In [127]:
# Numerical features
Alcohol = keras.Input(shape=(1,), name="Alcohol")
Malic_Acid = keras.Input(shape=(1,), name="Malic_Acid")
Ash = keras.Input(shape=(1,), name="Ash")
Ash_Alcanity = keras.Input(shape=(1,), name="Ash_Alcanity")
Magnesium = keras.Input(shape=(1,), name="Magnesium")
Total_Phenols = keras.Input(shape=(1,), name="Total_Phenols")
Flavanoids = keras.Input(shape=(1,), name="Flavanoids")
Nonflavanoid_Phenols = keras.Input(shape=(1,), name="Nonflavanoid_Phenols")
Proanthocyanins = keras.Input(shape=(1,), name="Proanthocyanins")
Color_Intensity = keras.Input(shape=(1,), name="Color_Intensity")
Hue = keras.Input(shape=(1,), name="Hue")
OD280 = keras.Input(shape=(1,), name="OD280")
Proline = keras.Input(shape=(1,), name="Proline")

In [128]:
all_inputs = [
    Alcohol,
    Malic_Acid,
    Ash,
    Ash_Alcanity,
    Magnesium,
    Total_Phenols,
    Flavanoids,
    Nonflavanoid_Phenols,
    Proanthocyanins,
    Color_Intensity,
    Hue,
    OD280,
    Proline,
]

In [129]:
all_inputs

[<KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Alcohol')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Malic_Acid')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Ash')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Ash_Alcanity')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Magnesium')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Total_Phenols')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Flavanoids')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Nonflavanoid_Phenols')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Proanthocyanins')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Color_Intensity')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Hue')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'OD280')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (crea

In [130]:
# Numerical features
Alcohol_encoded = encode_numerical_feature(Alcohol, "Alcohol", train_ds)
Malic_Acid_encoded = encode_numerical_feature(Malic_Acid, "Malic_Acid", train_ds)
Ash_encoded = encode_numerical_feature(Ash, "Ash", train_ds)
Ash_Alcanity_encoded = encode_numerical_feature(Ash_Alcanity, "Ash_Alcanity", train_ds)
Magnesium_encoded = encode_numerical_feature(Magnesium, "Magnesium", train_ds)
Total_Phenols_encoded = encode_numerical_feature(Total_Phenols, "Total_Phenols", train_ds)
Flavanoids_encoded = encode_numerical_feature(Flavanoids, "Flavanoids", train_ds)
Nonflavanoid_Phenols_encoded = encode_numerical_feature(Nonflavanoid_Phenols, "Nonflavanoid_Phenols", train_ds)
Proanthocyanins_encoded = encode_numerical_feature(Proanthocyanins, "Proanthocyanins", train_ds)
Color_Intensity_encoded = encode_numerical_feature(Color_Intensity, "Color_Intensity", train_ds)
Hue_encoded = encode_numerical_feature(Hue, "Hue", train_ds)
OD280_encoded = encode_numerical_feature(OD280, "OD280", train_ds)
Proline_encoded = encode_numerical_feature(Proline, "Proline", train_ds)

In [131]:
all_features = layers.concatenate(
    [
    Alcohol,
    Malic_Acid,
    Ash,
    Ash_Alcanity,
    Magnesium,
    Total_Phenols,
    Flavanoids,
    Nonflavanoid_Phenols,
    Proanthocyanins,
    Color_Intensity,
    Hue,
    OD280,
    Proline,
    ]
)

In [132]:
all_features

<KerasTensor: shape=(None, 13) dtype=float32 (created by layer 'concatenate_5')>

In [133]:
x = layers.Dense(32, activation="relu")(all_features)
x = layers.Dropout(0.5)(x)
# Plot Twist 2
output = layers.Dense(3, activation="softmax")(x)
model = keras.Model(all_inputs, output)
#Plot Twist 3
model.compile("adam", "categorical_crossentropy", metrics=["accuracy"])

In [134]:
model.fit(train_ds, epochs=100, validation_data=val_ds)

Epoch 1/100
5/5 [==============================] - 1s 57ms/step - loss: 148.8507 - accuracy: 0.2958 - val_loss: 72.3716 - val_accuracy: 0.5000
Epoch 2/100
5/5 [==============================] - 0s 15ms/step - loss: 135.0336 - accuracy: 0.3239 - val_loss: 61.0782 - val_accuracy: 0.5000
Epoch 3/100
5/5 [==============================] - 0s 15ms/step - loss: 124.0297 - accuracy: 0.2958 - val_loss: 49.9369 - val_accuracy: 0.5000
Epoch 4/100
5/5 [==============================] - 0s 18ms/step - loss: 112.7577 - accuracy: 0.2817 - val_loss: 39.6895 - val_accuracy: 0.5000
Epoch 5/100
5/5 [==============================] - 0s 18ms/step - loss: 120.7478 - accuracy: 0.2676 - val_loss: 31.6041 - val_accuracy: 0.5000
Epoch 6/100
5/5 [==============================] - 0s 18ms/step - loss: 95.5196 - accuracy: 0.3239 - val_loss: 22.5198 - val_accuracy: 0.5000
Epoch 7/100
5/5 [==============================] - 0s 21ms/step - loss: 99.8144 - accuracy: 0.3521 - val_loss: 14.7282 - val_accuracy: 0.5000
E

Epoch 59/100
5/5 [==============================] - 0s 12ms/step - loss: 13.3958 - accuracy: 0.5000 - val_loss: 1.8646 - val_accuracy: 0.7778
Epoch 60/100
5/5 [==============================] - 0s 15ms/step - loss: 11.7748 - accuracy: 0.4718 - val_loss: 2.1588 - val_accuracy: 0.7222
Epoch 61/100
5/5 [==============================] - 0s 13ms/step - loss: 11.0860 - accuracy: 0.5000 - val_loss: 2.3620 - val_accuracy: 0.7222
Epoch 62/100
5/5 [==============================] - 0s 14ms/step - loss: 11.3713 - accuracy: 0.5070 - val_loss: 2.5256 - val_accuracy: 0.7222
Epoch 63/100
5/5 [==============================] - 0s 15ms/step - loss: 12.4159 - accuracy: 0.4507 - val_loss: 2.7975 - val_accuracy: 0.6944
Epoch 64/100
5/5 [==============================] - 0s 15ms/step - loss: 12.8444 - accuracy: 0.4507 - val_loss: 2.7157 - val_accuracy: 0.6944
Epoch 65/100
5/5 [==============================] - 0s 17ms/step - loss: 10.5448 - accuracy: 0.4507 - val_loss: 2.6469 - val_accuracy: 0.7222
Epoch 

In [139]:
# sample with your own, do testing

test = wine.head(1)
test

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127            2.8   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1

In [140]:
# shortcut to convert dataframe to dict
test.drop('Customer_Segment',axis=1,inplace=True)

C:\Users\kexin_lee\Anaconda3\envs\python-dscourse\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [141]:
sample = test.to_dict('r')[0]

C:\Users\KEXIN_~1\AppData\Local\Temp/ipykernel_19812/1745375697.py:1: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  sample = test.to_dict('r')[0]


In [142]:
sample

{'Alcohol': 14.23,
 'Malic_Acid': 1.71,
 'Ash': 2.43,
 'Ash_Alcanity': 15.6,
 'Magnesium': 127,
 'Total_Phenols': 2.8,
 'Flavanoids': 3.06,
 'Nonflavanoid_Phenols': 0.28,
 'Proanthocyanins': 2.29,
 'Color_Intensity': 5.64,
 'Hue': 1.04,
 'OD280': 3.92,
 'Proline': 1065}

In [143]:
input_dict = {name: tf.convert_to_tensor([value]) for name, value in sample.items()}

In [144]:
input_dict

{'Alcohol': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([14.23], dtype=float32)>,
 'Malic_Acid': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.71], dtype=float32)>,
 'Ash': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.43], dtype=float32)>,
 'Ash_Alcanity': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([15.6], dtype=float32)>,
 'Magnesium': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([127])>,
 'Total_Phenols': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.8], dtype=float32)>,
 'Flavanoids': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.06], dtype=float32)>,
 'Nonflavanoid_Phenols': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.28], dtype=float32)>,
 'Proanthocyanins': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.29], dtype=float32)>,
 'Color_Intensity': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([5.64], dtype=float32)>,
 'Hue': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.04], dtype=float32)>,
 'OD280': 

In [145]:
predictions = model.predict(input_dict)

In [146]:
predictions

array([[0.97407496, 0.01917664, 0.0067484 ]], dtype=float32)

In [148]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

In [149]:
predictions

array([[0.974, 0.019, 0.007]], dtype=float32)

In [150]:
print(
    "This wine belongs to Type %d as evaluated by our model." % (predictions[0][0],)
)

This wine belongs to Type 0 as evaluated by our model.


*****************************************************

In [207]:
all_inputs_demo = []

for col in wine:
#   Condition to detect categorical columns
    if(wine[col].nunique()<=5):
        #   Condition to detect categorical columns + integer
        if(wine[col].dtypes=='int64'):
            all_inputs_demo.append(keras.Input(shape=(1,), name=col, dtype="int64"))
        #   Condition to detect categorical columns + string
        else:
            all_inputs_demo.append(keras.Input(shape=(1,), name=col, dtype="string"))
    #   Condition to detect numerical
    else:
        all_inputs_demo.append(keras.Input(shape=(1,), name=col))

In [208]:
all_inputs_demo

[<KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Alcohol')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Malic_Acid')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Ash')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Ash_Alcanity')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Magnesium')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Total_Phenols')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Flavanoids')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Nonflavanoid_Phenols')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Proanthocyanins')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Color_Intensity')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'Hue')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'OD280')>,
 <KerasTensor: shape=(None, 1) dtype=float32 (crea

In [209]:
colname= wine.columns[:-1]

In [210]:
for index,value in enumerate(colname):
    print(value)

Alcohol
Malic_Acid
Ash
Ash_Alcanity
Magnesium
Total_Phenols
Flavanoids
Nonflavanoid_Phenols
Proanthocyanins
Color_Intensity
Hue
OD280
Proline


In [178]:
features_encoded_demo =[]

for index,value in enumerate(colname):
#   Condition to detect categorical columns
    if(wine[value].nunique()<=5):
        #   Condition to detect categorical columns + integer
        if(wine[value].dtypes=='int64'):
            features_encoded_demo.append(encode_categorical_feature(all_inputs_demo[index], value, train_ds, False))
        #   Condition to detect categorical columns + string
        else:
            features_encoded_demo.append(encode_categorical_feature(all_inputs_demo[index], value, train_ds, True))
    #   Condition to detect numerical
    else:
        features_encoded_demo.append(encode_numerical_feature(all_inputs_demo[index], value, train_ds))

In [211]:
features_encoded_demo =[]
for index,value in enumerate(colname):
    features_encoded_demo.append(encode_numerical_feature(all_inputs_demo[index], value, train_ds))

In [212]:
all_features = layers.concatenate(features_encoded_demo)

In [213]:
all_features

<KerasTensor: shape=(None, 13) dtype=float32 (created by layer 'concatenate_7')>

In [214]:
x = layers.Dense(32, activation="relu")(all_features)
x = layers.Dropout(0.5)(x)
# Plot Twist 2
output = layers.Dense(3, activation="softmax")(x)
model = keras.Model(all_inputs, output)
#Plot Twist 3
model.compile("adam", "categorical_crossentropy", metrics=["accuracy"])

ValueError: Graph disconnected: cannot obtain value for tensor KerasTensor(type_spec=TensorSpec(shape=(None, 1), dtype=tf.float32, name='Alcohol'), name='Alcohol', description="created by layer 'Alcohol'") at layer "normalization_106". The following previous layers were accessed without issue: []

In [32]:
keras.utils.plot_model(model, show_shapes=True, rankdir="LR")

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model/model_to_dot to work.


In [182]:
model.fit(train_ds, epochs=100, validation_data=val_ds)

Epoch 1/100


ValueError: in user code:

    File "C:\Users\kexin_lee\Anaconda3\envs\python-dscourse\lib\site-packages\keras\engine\training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\kexin_lee\Anaconda3\envs\python-dscourse\lib\site-packages\keras\engine\training.py", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\kexin_lee\Anaconda3\envs\python-dscourse\lib\site-packages\keras\engine\training.py", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\kexin_lee\Anaconda3\envs\python-dscourse\lib\site-packages\keras\engine\training.py", line 859, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\kexin_lee\Anaconda3\envs\python-dscourse\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\kexin_lee\Anaconda3\envs\python-dscourse\lib\site-packages\keras\engine\input_spec.py", line 183, in assert_input_compatibility
        raise ValueError(f'Missing data for input "{name}". '

    ValueError: Missing data for input "Customer_Segment". You passed a data dictionary with keys ['Alcohol', 'Malic_Acid', 'Ash', 'Ash_Alcanity', 'Magnesium', 'Total_Phenols', 'Flavanoids', 'Nonflavanoid_Phenols', 'Proanthocyanins', 'Color_Intensity', 'Hue', 'OD280', 'Proline']. Expected the following keys: ['Alcohol', 'Malic_Acid', 'Ash', 'Ash_Alcanity', 'Magnesium', 'Total_Phenols', 'Flavanoids', 'Nonflavanoid_Phenols', 'Proanthocyanins', 'Color_Intensity', 'Hue', 'OD280', 'Proline', 'Customer_Segment']
